spring.application.name=cinehome
server.port=8080

# MariaDB \uC811\uC18D \uD3EC\uD2B8
spring.datasource.url=jdbc:mariadb://localhost:3307/cinehome
spring.datasource.username=root
spring.datasource.password=root


# Mybatis, Mapper \uC124\uC815
mybatis.mapper-locations=classpath:mapper/**/*.xml
# Mybatis\uAC00 \uBCC4\uCE6D \uD328\uD0A4\uC9C0 \uC9C0\uC815
#mybatis.type-aliases-package=com.cinehome
mybatis.type-aliases-package=com.cinehome.member.domain, com.cinehome.movie.domain, com.cinehome.review.domain


# Mybatis\uB85C \uCE74\uBA5C\uD45C\uAE30\uBC95 (\uB9C8\uC774\uBC14\uD2F0\uC2A4\uAC00 \uC790\uB3D9\uBCC0\uD658)
mybatis.configuration.map-underscore-to-camel-case=true
